apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service_name }}
  labels:
    app:  {{ .Values.label_name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app:  {{ .Values.label_name }}
